name: orbitrx
description: A minimal Flutter app for ORBITRIX
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^2.0.0
  permission_handler: ^11.0.0
  location: ^5.0.3
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geocoding: ^2.1.1
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

